enum AthleticsEventTypes {
  MEN_1500 = "1500m (M)",
  WOMEN_1500 = "1500m (W)",
  MEN_800 = "800m (M)",
  WOMEN_800 = "800m (W)",
  MEN_400 = "400m (M)",
  WOMEN_400 = "400m (W)",
  MEN_200 = "200m (M)",
  WOMEN_200 = "200m (W)",
  MEN_100 = "100m (M)",
  WOMEN_100 = "100m (W)",
  MEN_110_HURDLES = "110m Hurdles (M)",
  WOMEN_110_HURDLES = "110m Hurdles (W)",
  MEN_400_HURDLES = "400m Hurdles (M)",
  WOMEN_400_HURDLES = "400m Hurdles (W)",
  MEN_HAMMER_THROW = "Hammer Throw (M)",
  WOMEN_HAMMER_THROW = "Hammer Throw (W)",
  MEN_DISK_THROW = "Discus Throw (M)",
  WOMEN_DISK_THROW = "Discus Throw (W)",
  MEN_POLE_VAULT = "Pole Vault (M)",
  WOMEN_POLE_VAULT = "Pole Vault (W)",
  MEN_SHOT_PUT = "Shot Put (M)",
  WOMEN_SHOT_PUT = "Shot Put (W)",
  MEN_TRIPLE_JUMP = "Triple Jump (M)",
  WOMEN_TRIPLE_JUMP = "Triple Jump (W)",
  MEN_JAVELIN_THROW = "Javelin Throw (M)",
  WOMEN_JAVELIN_THROW = "Javelin Throw (W)",
  MEN_HIGH_JUMP = "High Jump (M)",
  WOMEN_HIGH_JUMP = "High Jump (W)",
  MEN_LONG_JUMP = "Long Jump (M)",
  WOMEN_LONG_JUMP = "Long Jump (W)",
  MEN_4X100 = "4x100m (M)",
  WOMEN_4X100 = "4x100m (W)",
}

export default AthleticsEventTypes;
